typography_spectrum: 0.48188326694071293
color:
  brandStrength: 0.384326112922281
  lightness: 0.4784296448342502
  saturation: 0.09175616526044905
  rhythmicContrast: 0.40394032886251807
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.8072817379143089
name: Gabrial Reising Photography
title: Gabrial Reising Photography
description: 'Capturing Inner Light '
